### ISSUE TITLE
GitLab error 404

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/gitlab_ynh#105]
After signing to gitLab with LDAP username and password, GitLab opens a page  `https://gitlab.domain.ltd/ynhtheme/custom_overlay.css` with 404 error.
(If I go to `https://gitlab.domain.ltd/` I can see that I am connected and have a functional interface)

**Comment by kay0u** [comment]
Hello and thank you for the report.

I've seen this error before, but I can't reproduce it 100%. Sometimes I don't get redirected. I'll look into that when I have some time...

**Comment by kay0u** [comment]
I think I found the problem, you can follow the discussion about this fix here: https://github.com/YunoHost/yunohost/pull/925

**Comment by curious-jeremy** [comment]
I confirm I have the same issue, and https://github.com/YunoHost/yunohost/pull/925 fixes it :ok_hand:
