### ISSUE TITLE
Fix warning : 'yunohost app checkurl' is deprecated

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gitlab_ynh#11]
the installation logs report this warning

**Comment by bourreP** [comment]
I have the same thing, but, didn't find any remplacement for this function at this moment.

**Comment by Rafi594** [comment]
I' ll add the new helpers for this

```
# Check web path availability
ynh_webpath_available "$domain" "$path_url"
# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"
```

**Comment by bourreP** [comment]
Hi, it's fixed during the installation. Thanks for your report.
