### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/gitlab_ynh#12]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/gitlab%20(Community)/5/console

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by Christophe31** [comment]
servers went from jessie to stretch, so, I suppose, you need to update your .list file at least.

**Comment by bourreP** [comment]
This app is level 7 now. So I close this issue.
