### ISSUE TITLE
Default ports are not checked

### ISSUE THREAD

**Issue by scharc** [YunoHost-Apps/gitlab_ynh#127]
Gitlab nginx defaults to 8080 which in some case is already used... 
In my case it was spellchecker from onlyOffice 
See here: https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/27

I would suggest that gitlab tries to get free ports from ynh_check_ports() and reconfigure all services according.

**Comment by kay0u** [comment]
Hi,

Gitlab is looking for an available port:

https://github.com/YunoHost-Apps/gitlab_ynh/blob/a8dde1600e92c9dcb709f02f879eb80ac8ba7626/scripts/install#L89

Can you please provide the logs of the install script?

**Comment by scharc** [comment]
OK, so it is a onlyOffice problem
