### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/gitlab_ynh#13]
Hello i have this error 👍 

```
root@YunoHost:~# sudo yunohost app upgrade --verbose gitlab -u https://github.com/YunoHost-Apps/gitlab_ynh
Upgrading apps gitlab
Warning: Upgrading app gitlab...
Error: gitlab is not installed

```

what do u thikn please

**Comment by Rafi594** [comment]
Why do you use yunohost app upgrade ?

For install you have to use sudo yunohost app install https://github.com/YunoHost-Apps/gitlab_ynh or use the webadmin.

**Comment by bourreP** [comment]
Hi, I close this issue for inactivity. If you need some help, you can response to this one or open another.
