### ISSUE TITLE
can't change any general settings 500 error

### ISSUE THREAD

**Issue by sxenny** [YunoHost-Apps/gitlab_ynh#130]
Hello

I have yunohost where I installed gitlab 13.5.1 

If I go to Admin area-> Settings-> Genaral-> select any "expand" and try to save change I got an error page 

```
"500
Whoops, something went wrong on our end.
Try refreshing the page, or going back and attempting the action again.

Please contact your GitLab administrator if this problem persists."


```
First I think it's nginx setting and check it /etc/nginx/conf.d/my_domain/gitlab.conf:

```
"
location /gitlab/ {
        # Adapted from https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/web-server/nginx/gitlab-omnibus-ssl-nginx.conf

        client_max_body_size 250m;
        gzip off;

        ## https://github.com/gitlabhq/gitlabhq/issues/694
        ## Some requests take more than 30 seconds.
        proxy_read_timeout      300;
        proxy_connect_timeout   300;
        proxy_redirect          off;

        proxy_http_version 1.1;

        proxy_pass http://localhost:8080;

        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-Ssl     on;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;

        # Include SSOWAT user panel.
        include conf.d/yunohost_panel.conf.inc;
}
"
```

**Comment by kay0u** [comment]
Hi,

I think it's more related to Gitlab, but anyway, do you have errors in `YunoHost Admin -> Services -> gitlab-runsvdir` ?

I can find a similar issue [here](https://gitlab.com/gitlab-org/gitlab/-/issues/26171), but if you want to try [this fix](https://gitlab.com/gitlab-org/gitlab/-/issues/26171#note_215596084) for example, please make a backup before, just in case :smile:

**Comment by sxenny** [comment]
@kay0u 
Hi, 
Thanks
You're right It fixed by https://gitlab.com/gitlab-org/gitlab/-/issues/26171#note_215596084

**Comment by kay0u** [comment]
I'm glad you fixed it!

Closing this issue, please feel free to reopen it if needed.
