### ISSUE TITLE
gitlab-backup missing

### ISSUE THREAD

**Issue by electrocuted-slug** [YunoHost-Apps/gitlab_ynh#132]
## :uk:/:us:   Message template (english)

Hello everyone, my first post on the issue.

### My YunoHost server

**Hardware:** VPS bought online ...
**YunoHost version:**  
yunohost: 
  repo: stable
  version: 4.0.8
yunohost-admin: 
  repo: stable
  version: 4.0.4
moulinette: 
  repo: stable
  version: 4.0.3
ssowat: 
  repo: stable
  version: 4.0.4.1

**I have access to my server :** Through SSH
**Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?** : no

### Description of my issue

```shell
sudo yunohost app upgrade
# key errors
# WARNING - 1271 /tmp/backup_fLQsbD: line 51: gitlab-backup: command not found
# ERROR - Could not upgrade gitlab: An error occurred inside the app upgrade script
```
[https://paste.yunohost.org/raw/afofomaxey](https://paste.yunohost.org/raw/afofomaxey)

--------------------------------------------------

**Comment by kay0u** [comment]
Hi!

I'm sorry that you are facing such an issue.

First of all, can I have the result of `sudo gitlab-rake gitlab:env:info` (it might take a little while).

Then can you give me the result of:

```
which gitlab-ctl
# and
which gitlab-backup
```

**Comment by electrocuted-slug** [comment]
@kay0u They all return empty.
```shell
user@yunohost:~$ sudo gitlab-rake gitlab:env:info
sudo: gitlab-rake: command not found
user@yunohost:~$ which gitlab-rake
user@yunohost:~$ which gitlab-backup
user@yunohost:~$ which gitlab-ctl
user@yunohost:~$
```

**Comment by kay0u** [comment]
It's really weird.

Do you have access to gitlab with your browser?

Maybe, check if Gitlab is installed in Yunohost, but if you can start the upgrade, it should be:
```
sudo yunohost app list | grep gitlab
```

Then `ls /opt/gitlab/` to make sure the files exist?

**Comment by electrocuted-slug** [comment]
```shell
:~$ sudo yunohost app list | grep gitlab
    id: gitlab
:~$ ls /opt/gitlab
ls: cannot access '/opt/gitlab': No such file or directory
```
I think I might have broke the upgrade somehow mid upgrade.
I had a connection issue over ssh mid update with yunohost.
Is it possible to break GitLab this way?

**Comment by kay0u** [comment]
> I think I might have broke the upgrade somehow mid upgrade.
> I had a connection issue over ssh mid update with yunohost.
> Is it possible to break GitLab this way?

Yes absolutely! If you think your ssh connection can stop, you should use the admin panel instead (or use nohup, tmux...)

The best thing to do is to remove the broken app with `yunohost app remove gitlab` (or the web admin) and restore the latest backup of gitlab

**Comment by electrocuted-slug** [comment]
Thanks so much, where will I find this backup?

**Comment by electrocuted-slug** [comment]
Found it.
```shell
cp /home/yunohost.backup/tmp/gitlab-pre-upgrade2/apps/gitlab/backup/var/opt/gitlab/backups/last_gitlab_backup.tar /home/yourhome/last_gitlab_backup.tar 
sudo yunohost app remove gitlab
sudo yunohost app install gitlab
```
[How to Restore](https://docs.gitlab.com/ce/raketasks/backup_restore.html#restore-for-omnibus-gitlab-installations)

**Comment by kay0u** [comment]
Hmm, you can do it like that if you want, but don't forget to copy `gitlab-secrets.json` and `gitlab.rb` in `/etc/gitlab/`. But the easier way to do it (if you have any recent backup) is to use the restore system of Yunohost.
With the webadmin:
Backup->Local archives->And the more recent backup of gitlab
With the cli:
```
sudo yunohost backup list
# you can get information about creation date, content of your backup (you can check if gitlab is present in the backup) with:
sudo yunohost backup info a_backup_name -dH
sudo yunohost backup restore a_backup_name --apps gitlab
```

And it will take care for of copying everything for you.

That being said, as your ssh connection broke during an upgrade, I hope the `last_gitlab_backup.tar` file you used is complete to restore gitlab, it may be corrupted. If you think everything is working fine after doing your restore (check especially the runner part of the gitlab admin, you can get some errors if you don't have `gitlab-secrets.json` correctly restored), then you are safe, and you can continue to use it :+1: 

<sup>but please don't use raw ssh to upgrade gitlab as it can take a lot of time and break again :angel: </sup>

**Comment by electrocuted-slug** [comment]
Pro tip for anybody using ssh.
Using screen or tmux really helps the install if you have poor ssh connection.

**Comment by electrocuted-slug** [comment]
Yeah I followed your instructions. Perfect!

**Comment by kay0u** [comment]
I'm closing the issue, feel free to reopen it if needed
