### ISSUE TITLE
Installation script error on arm64

### ISSUE THREAD

**Issue by Clemorange22** [YunoHost-Apps/gitlab_ynh#145]
Hello,
I have an error while installing gitalab on arm64,
the logs are here : 
https://paste.yunohost.org/raw/uguxuzoxox
Can someone help me ?

**Comment by Christophe31** [comment]
It looks like this issue: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/3165
Did you enable let's encrypt for your gitlab domain?
