### ISSUE TITLE
SSH key login failing

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#152]
Hi, I upgraded both yunohost to 4.2 and gitlab, but since then, I cant use git ssh key authentication…
```
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
```
Not sure what to look for, but it broke on multiple git client computers at the same time. Is the new yunohost ssh/sftp permission causing this?

**Comment by kay0u** [comment]
Hi!

> Not sure what to look for, but it broke on multiple git client computers at the same time. Is the new yunohost ssh/sftp permission causing this?

Yes probably, to fix this issue, please add the user `git` to the `ssh.app` group

**Comment by Christophe31** [comment]
As git is not a yunohost user, I'm not sure how to do that…

**Comment by Christophe31** [comment]
Thx, indeed, it fixes git sync.
