### ISSUE TITLE
subscription tab missing

### ISSUE THREAD

**Issue by haydenwalker980** [YunoHost-Apps/gitlab_ynh#173]
When I go to the Admin Area to activate a license I cannot find the subscription tab.

**Comment by kay0u** [comment]
Hi,

This is because this package install the GitLab Community Edition (CE) with an MIT License, and not the GitLab Enterprise Edition (EE) with

**Comment by haydenwalker980** [comment]
Ah

It's really needed in this case and so I would like a migration script
