### ISSUE TITLE
Critical Security Release 14.8.2 CERTFR-2022-AVI-189

### ISSUE THREAD

**Issue by Taekiro** [YunoHost-Apps/gitlab_ynh#177]
Multiple vunerabilities on GitLab products. Upgrade strongly recommend. 

https://www.cert.ssi.gouv.fr/avis/CERTFR-2022-AVI-189/

https://about.gitlab.com/releases/2022/02/25/critical-security-release-gitlab-14-8-2-released/

**Comment by kay0u** [comment]
Thank you, should be merged soon
