### ISSUE TITLE
502 after adding pages in the configuration

### ISSUE THREAD

**Issue by julientaq** [YunoHost-Apps/gitlab_ynh#182]
### Describe the bug

Installed gitlab (works perfectly)
Then prepare everything to have working pages (i have a gitlabrunner next to yunohost and a subdomain for the pages).
I add the infos for the pages in the `gitlab-persistent.rb` and then `sudo gitlab-ctl reconfigure`.

added those: 

```
pages_external_url "suddomain.something.sth"
gitlab_pages['enable'] = true
```

After that, gitlab is running but i can’t access it through my server and get a 502 bad getaway. 

### Context

Home server with latest yunohost.

### Steps to reproduce

Set up the pages in the persistent config.

### Expected behavior

Gitlab restarts and pages settings is now available

### LOG

gitlabctl-status

```
run: alertmanager: (pid 1964) 443s; run: log: (pid 1963) 443s
run: gitaly: (pid 1982) 443s; run: log: (pid 1960) 443s
run: gitlab-exporter: (pid 1957) 443s; run: log: (pid 1956) 443s
run: gitlab-kas: (pid 1940) 443s; run: log: (pid 1937) 443s
run: gitlab-pages: (pid 1958) 443s; run: log: (pid 1955) 443s
run: gitlab-workhorse: (pid 1972) 443s; run: log: (pid 1968) 443s
run: grafana: (pid 1961) 443s; run: log: (pid 1959) 443s
run: logrotate: (pid 1973) 443s; run: log: (pid 1969) 443s
down: nginx: 0s, normally up, want up; run: log: (pid 1988) 443s
run: node-exporter: (pid 1950) 443s; run: log: (pid 1945) 443s
run: postgres-exporter: (pid 1975) 443s; run: log: (pid 1966) 443s
run: postgresql: (pid 1932) 443s; run: log: (pid 1929) 443s
run: prometheus: (pid 1928) 443s; run: log: (pid 1927) 443s
run: puma: (pid 1949) 443s; run: log: (pid 1939) 443s
run: redis: (pid 1965) 443s; run: log: (pid 1962) 443s
run: redis-exporter: (pid 1983) 443s; run: log: (pid 1979) 443s
run: sidekiq: (pid 1971) 443s; run: log: (pid 1967) 443s
```

**Comment by kay0u** [comment]
Gitlab pages are not a simple problem for YunoHost because we don't manage wildcard domains, I don't have a solution yet.

You can always take a look at your logs with :
```
# tail -f /var/log/gitlab/**/current
```

**Comment by julientaq** [comment]
Yeah, i got that. And worse, gitlab pages need 2 different IP. So it’s unlikely to work with YunoHost.

My next option is to look at [coolify](https://coolify.io/) to handle the build/serve.

Thanks a lot for your answer, i’ll close this issue!
