### ISSUE TITLE
Remove gitlab-ce

### ISSUE THREAD

**Issue by GuillermoAnkh** [YunoHost-Apps/gitlab_ynh#191]
Hi, i found something that block me when i try to remove Gitlab from my server. I don't know what to do if you have an idea
Thanks a lott

I try to remove Gitlab from my server. But since i can update anything or install nex thing. I try . -`-fix-broken` et `dpkg --configure -a` don't work

When i try to list packet i have this 
ii git
ii git-man
rHR gitlab-ce
ii gitlab-ynh-deps

I try to remove them one by one but gitlab -ce block the process every time.
The command lign dpkg audit show this

```
Les paquets suivants sont dans un état incohérent à cause de sérieux
problèmes survenus lors de l'installation. Ils doivent être réinstallés
(ainsi que tous les paquets qui en dépendent) pour pouvoir fonctionner
correctement :
 gitlab-ce            GitLab Community Edition (including NGINX, Postgres, Redi

Les paquets qui suivent ne possèdent pas de fichier de somme de contrôle MD5 dans
la base de données et doivent être réinstallés :
 gitlab-ce            GitLab Community Edition (including NGINX, Postgres, Redi
```

I don't know how to repare this with out killing all my server. Please thank a lot for your help
Merci pour votre aide.

**Comment by kay0u** [comment]
Hi, if you really want to remove gitlab-ce package, and the Yunohost app "Gitlab" is no longer installed (may I get the remove gitlab logs to try to understand and fix the issue on my side?), you can do something like that:

```
sudo dpkg --remove --force-all gitlab-ce
```

similar problem here: https://askubuntu.com/questions/422696/package-is-in-a-very-bad-inconsistent-state
