### ISSUE TITLE
Why SWAP is mandatory ?

### ISSUE THREAD

**Issue by Cellophile** [YunoHost-Apps/gitlab_ynh#231]
### Adding a SWAP file

If we have a machine with a lot of RAM, and a SSD disk, we don't want put a SWAP file on it.

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 11.2.5 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain:

### Steps to reproduce
Just install or update a git app. 

Is it possible to let us the choice to authorize git to verify and add a SWAP, or not ?
In the app settings, you should add a parameter about this, and verify if a SWAP is already existing or not only if the admin has decided that.

For example, I have on my machine 20Go of RAM, and only few services on it, and a SSH disk, so I don't want to use SWAP file. 
Currently, I have to uninstall the SWAP file after each update ! :)

Thanks a lot !

**Comment by kay0u** [comment]
When I wrote this package, it was [strongly recommended](https://archives.docs.gitlab.com/14.10/ee/install/requirements.html#memory) to have at least 2GB of swap

But things have changed. Nowadays, if the server has at least 4GB of RAM, it's [no longer recommended](https://docs.gitlab.com/ee/install/requirements.html#memory) to have SWAP (or [even the opposite](https://docs.gitlab.com/ee/administration/reference_architectures/index.html#no-swap)).

I'll try to find some time to remove the swap file if the machine has more than 4Go of RAM.

Thanks for the issue!

**Comment by kay0u** [comment]
Merged in stable, coming with 16.5.0
