### ISSUE TITLE
Bad admin account: The sequel

### ISSUE THREAD

**Issue by haydenwalker980** [YunoHost-Apps/gitlab_ynh#245]
### Describe the bug

The user created does not receive admin permissions.

### Context

- Hardware: Google Cloud Platform
- YunoHost version: 11.2.9.1
- I have access to my server: Thru SSH/webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: Latest
- 
### Steps to reproduce

- Install GitLab and specify the admin user. Log in and OOPS the admin access just didn't work.

### Expected behavior

- The created user should be an admin.

### My hypothesis

Last time it was the user not being saved with `.save!` however that fix did not work. My guess is probably the sequence in which the commands are run is incorrect, because that exact statement works post-install. I'll debug this further on a fork.

**Comment by kay0u** [comment]
Should be fixed in testing (I'm waiting the next gitlab release to publish it)
