### ISSUE TITLE
WebIDE/VScode integration no longer opens/authenticates.

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#264]
### Describe the bug
gitlab web vscode integration stops in authentication phase

### Context

- Hardware: dedicated server
- YunoHost version: 11.2.30.2 (stable)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - I made last upgrade
  - I changed SSH port from 22 to 122 and then back to 22 when I saw gitlab remotes where broken.

### Steps to reproduce

On any project try to open in WebIDE:
![image](https://github.com/user-attachments/assets/fcc50540-505f-419c-b6b5-74022cfe8be8)

It fails to authenticate:
![image](https://github.com/user-attachments/assets/e4264d59-f2a0-4e8f-9bb2-d47f0bb663c6)

### Expected behavior
We should land to a web vscode interface.

### Logs

```
Uncaught (in promise) Error: Something bad happened while getting OAuth token: {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
```

**Comment by kay0u** [comment]
I'm trying something https://github.com/YunoHost-Apps/gitlab_ynh/pull/265

**Comment by Christophe31** [comment]
weirdly, I worked today on my same instance, not sure what happened or if others instances had/have the issue…

**Comment by kay0u** [comment]
Yes, I was able to reproduce the issue on my instance but sometimes it works well

**Comment by kay0u** [comment]
Oupsie, was auto closed with the merge. Please feel free to reopen if needed
