### ISSUE TITLE
Migration crash

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#29]
Hi, As you provided migration which allow ynh 2.7 gitlab users to upgrade  to ynh 3+, I just did but the github migration don't look like a great success: [logs](https://paste.yunohost.org/uzukakovoq.sql)

I guess it may have more sense in the form than here, but I don't know how topics are handled there.

It may be linked to the fact I tweaked a bit gitlab's nginx files to avoid ynh integration as the ynh token was required but did not authenticate at the time… so I removed the ynh button and token, don't know if it may be linked and if there is a way to roll back.

**Comment by kay0u** [comment]
Hi, thank you for your report.

It's due to a very old package which didn't store all parameters used in the upgrade script. I'll try to fix it today!

**Comment by Christophe31** [comment]
I redeployed on a new server after the migration failed, but the backup didn't had any of the repositories ^^. As the migration failed it rolled back to the not working backup and erased everything.

**Comment by kay0u** [comment]
(Sorry, I didn't want to close this issue.)

In the old version, the backup/restore was not implemented and since then I have reworked everything.

I hope you didn't lose anything...

Do not hesitate to tell me if you have another problem with gitlab.

I'll open a topic on the forum about gitlab app.

**Comment by kay0u** [comment]
I just opened a new topic on the forum:

https://forum.yunohost.org/t/gitlab-a-git-repository-manager/7499

I close this issue. Feel free to open a new one if needed.
