### ISSUE TITLE
New install - 502 Bad Gateway

### ISSUE THREAD

**Issue by Ptibibi** [YunoHost-Apps/gitlab_ynh#33]
I've reinstall all my system on my OVH server (Debian 9 x64).
All my applications are working fine except Gitlab. I have an error message saying "502 Bad Gateway".

Thanks.

**Comment by Ptibibi** [comment]
The problem was solved after several server reboot.

**Comment by kay0u** [comment]
Hi,

This is not an issue, gitlab just take some time to start all his services (it's mainly depend on your server)

Don't hesitate if you have another problem!
