### ISSUE TITLE
Disable services on update

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#43]
I don't know if it's still present but I upgrade from a version you made 1 month ago, (when I complained about the lack of backup of the previous maintainer which wiped my data). It disabled our container registry, I had to edit `gitlab.rb` again.

**Comment by kay0u** [comment]
Hi,

What you are looking for is an option not to overwrite this file?

I can implement this feature and release it for the next version of gitlab. (Btw next version will come with the correction of some bugs inside this file)

**Comment by Christophe31** [comment]
I don't know, but, I was suprised I had to redo my registry config as this behavior wasn't documented in the upgrade warning.

I don't know what you feel like a good solution but to me it took me a bit of time to see why pipelines didn't worked, understand and reconfigure it all.

If a third party did the config and I didn't had the skill my self, it would have been a bigger issue.

**Comment by kay0u** [comment]
Hi,

I'll merge https://github.com/YunoHost-Apps/gitlab_ynh/pull/42

If you don't want that the upgrade overwrite `gitlab.rb` you can do that before the upgrade:

```bash
source /usr/share/yunohost/helpers

ynh_app_setting_set gitlab overwrite_gitlab_config "0"
```

With this, the configuration file will never be overwrite again.

But be careful, I've added :
`gitlab_rails['gitlab_shell_ssh_port'] = __SSH_PORT__` where `__SSH_PORT__` is the ssh port (if the ssh port of your server is not 22, you have to add this line to your config file).

`sidekiq['listen_port'] = __SIDEKIQ_PORT__` where `__SIDEKIQ_PORT__` corresponding to the value returned by (after the upgrade):
```bash
ynh_app_setting_get gitlab sidekiq_port
```

And:
`nginx['client_max_body_size'] = '__CLIENT_MAX_BODY_SIZE__'` where `__CLIENT_MAX_BODY_SIZE__` is the value returned by (after the upgrade):
```bash
ynh_app_setting_get gitlab client_max_body_size
```

**Comment by Christophe31** [comment]
or would it be possible to have an include? (I'm not a ruby user but in django you often see loading of a unversionned local file for local config) with ``from local_file import *`` so you can update the main config file but we can update values to override what we want.

**Comment by kay0u** [comment]
That's a good idea, i'll test that :-)

**Comment by kay0u** [comment]
The file: `/etc/gitlab/gitlab-persistent.rb` will be created, you can put your configuration inside it!

**Comment by kay0u** [comment]
It's merged, you can create the file `/etc/gitlab/gitlab-persistent.rb` with your conf before launching the upgrade :-) Don't hesitate to give me feedback about this feature!

**Comment by Christophe31** [comment]
thx for the info, I'll look into it tomorrow.

**Comment by Christophe31** [comment]
It worked great, maybe a visible warning in the /etc/gitlab/gitlab.rb to suggest to modify the -persistant.rb instead as this file is generated/overiten on updates.

Thanx for your support.
