### ISSUE TITLE
Releases process

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#45]
Hello, I'm looking on your release process.

I saw that yesterday, there was a security patch which seems to be "strongly recommanded" https://about.gitlab.com/2019/04/29/security-release-gitlab-11-dot-10-dot-2-released/ 

I there a way for me to make easily an upgrade script? to test it? I didn't looked deeply into it.

Or is your release process based on the fact there are release version every month (the 22 th) and you will ignore the fixes patches until the next feature version?

To me both make sense but I would like to know your vision on how you want to follow gitlab version if you do it manually.

**Comment by kay0u** [comment]
Hi,

I follow this plan:

Every fee days I go to this website: https://packages.gitlab.com/gitlab/, where I download the .deb in the update/install script of YunoHost. I modify the file: https://github.com/YunoHost-Apps/gitlab_ynh/blob/master/scripts/upgrade.d/upgrade.last.sh with the latest version, the sha256sum for x86_64 and arm. I update the README.md and the manifest.json with the right version, I make a PR, test it with package_check, and if everything works, I merge it. 

For example, the sha256sum of the version 11.10.2 can be found here for x86_64:
https://packages.gitlab.com/gitlab/gitlab-ce/packages/debian/stretch/gitlab-ce_11.10.2-ce.0_amd64.deb
And here for arm:
https://packages.gitlab.com/gitlab/raspberry-pi2/packages/raspbian/stretch/gitlab-ce_11.10.2-ce.0_armhf.deb

For x86_64, I use the version debian/stretch here: https://packages.gitlab.com/gitlab/gitlab-ce and for arm, I use raspbian/stretch here: https://packages.gitlab.com/gitlab/raspberry-pi2 

If you a new version, PR are welcome with files updated as described above, I'll check with package_check, and merge them with pleasure.

I commit the new version in the branch testing: https://github.com/YunoHost-Apps/gitlab_ynh/commit/749a286553d36cffef0656e33abb0103ac17dbb8
I'll create the PR, and package_check it.

**Comment by Christophe31** [comment]
I follow the gitlab RSS so I get notified by the updates, I may not see it right away but most of the time I find their blog rather interesting so I read most of their posts.

The commit diff is a good doc on how to propose a new release indeed thanx for the quick answer and the update.

**Comment by kay0u** [comment]
I close this PR, feel free to open a new one if something else is not clear, or if you see a new version (PR are welcome too :-))

PS: v11.10.4 will be tested soon
