### ISSUE TITLE
Does yunohost nginx authentication prevent tooling?

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#5]
Hi, can gitlab integrate with tools & things with ynh authentication? Can the API part of gitlab be open, or is it already? Would MatterMost or Sentry be able to join gitlab to update issues?

(Ok, this question seems easy enough so I should probably try before asking, but, it looks like a real question which may interest others, as ynh also propose to install mattermost…)

**Comment by Christophe31** [comment]
Most pages from gitlab are protected by nginx ldap integration, so If I use a tool (for exemple getsentry) which use gitlab api (to report issues from automatic bug report in this exemple), how does it pass throught the yunohost ldap nginx control ?

**Comment by bourreP** [comment]
I don't have getsentry, but slack. I can use the `Slack notifications` and `Slack slash commands`. Everything is working for me.

**Comment by Christophe31** [comment]
Does your gitlab instance have a slack user with it's own api key?

**Comment by bourreP** [comment]
It's fully integrated to gitlab. No need to add a slack user. You just have to give a Token for the `Slack slash commands` and register the command in Slack admin panel, and for the `Slack notifications` gitlab use a webhook.

**Comment by bourreP** [comment]
That answers your question? :-)

**Comment by Christophe31** [comment]
I'm not sure, how do you gen the slack token?

**Comment by bourreP** [comment]
Everything is explained in the corresponding page of gitlab, but you just have to follow this link : [slash-commands](https://my.slack.com/services/new/slash-commands) add a command (login if it's necessary), and Slack will give you the Token.

I assume that it's the same thing for Mattermost.

**Comment by kay0u** [comment]
Is it ok for you?

**Comment by kay0u** [comment]
I close this issue, don't hesitate to open a new one if you need some help
