### ISSUE TITLE
fallocate: fallocate failed: Operation not supported

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/gitlab_ynh#52]
Well, I know, that isn't just about this app but about the helper `ynh_add_swap`, still, as you're probably the first to really using that helper.
Let's fix that where we can really test it.

fallocate may sometime not be used, I had this error on my Virtual Machine, trying to install your app for https://github.com/YunoHost/apps/pull/767.
Still, we should try to use it when available, fallocate takes 0,162s to create a 7G swap file.

But in case fallocate isn't available, dd can be used instead
```
dd if=/dev/zero of=/swap_$app bs=1024 count=${swap_size}
```
It takes 23s to do the same file though...

A small file, 1k, could be used to try fallocate at the beginning of the helper.

**Comment by kay0u** [comment]
Something like:

```bash
if ! fallocate -l ${swap_size}K /swap_$app
then
    dd if=/dev/zero of=/swap_$app bs=1024 count=${swap_size}
fi
```

Should be ok no?

**Comment by maniackcrudelis** [comment]
I'm not sure it wouldn't trig TRAP.
I'm going to try that on another VM.
Still waiting on the first one to finish to install... That's really long !

**Comment by maniackcrudelis** [comment]
Yep, that's ok, fallocate failed and dd was used instead.
A small explanation though would be welcome.
Aside of that point, you can do that

**Comment by kay0u** [comment]
Thank you for your tests!

https://github.com/YunoHost-Apps/gitlab_ynh/commit/951a1bbf9c299d6eac588a4f6e8d3c9b792575e4

I package_check with this new commit and if everything is ok, I merge it, and update the corresponding helper in https://github.com/YunoHost-Apps/Experimental_helpers
