### ISSUE TITLE
Needs more details about this repo

### ISSUE THREAD

**Issue by Krands** [YunoHost-Apps/gitlab_ynh#6]
Hello,

I have few questions about Gitlab here. Can you tell which edition of Gitlab is it? 
I know there are 2 possibles : the Community and the Entreprise Edition Starter.

So my question is:
> _Do you provide yourself the LDAP support or do you pay the EES and package the latter?_

**Comment by strictosensus** [comment]
hi,

you're right, there is 2 version. This is a gitlab CE. 
LDAP is working on both version. there is just more feature in EE. 

> extract from https://docs.gitlab.com/ce/administration/auth/ldap.html
GitLab integrates with LDAP to support user authentication. This integration works with most LDAP-compliant directory servers, including Microsoft Active Directory, Apple Open Directory, Open LDAP, and 389 Server. GitLab EE includes enhanced integration, including group membership syncing.

**Comment by Krands** [comment]
Okay, thank you!

Also, is there any option to upgrade it locally in the event I want to without having to have to install the EES and put the CE out? As you are packaging it, you might have seen this.

**Comment by strictosensus** [comment]
I'm not the main packager, i helped on install script and LDAP link. 

All i can say about EES upgrade from CE is that it is probably the same steps as explain on official gitlab documentation. 
this package is not yet design for install EES. if you can upgrade your gitlab from CE, it would be nice.

keep in mind : this package is not yet terminated. backup and upgrade yunohost script are not yet working.

**Comment by Zykino** [comment]
I'm hijacking a bit this tread to ask: What is the package status?
On https://yunohost.org/ the package is shown as InProgress with a note of 0.

I understand that a backup script not ready means I won't be able to migrate or save my data (fortunately git isn't centralized.).
Upgrade script missing is a bit more problematic (I would like to keep my gitlab instance as up to date as possible)

But what about usability? Is the ynh integration done or are there some things you should do before a lambda developer (not sysadmin) can install this app? No problem for ugrades when it will be done?

**Comment by Krands** [comment]
> keep in mind : this package is not yet terminated. backup and upgrade yunohost script are not yet working.

I am planning for now to install a new Yunohost instance on a more powerful machine, so it does not matter.

But yes, if I can get the EES from this package it would be actually great.

**Comment by Zykino** [comment]
While I'm here, my concerns could  be resolved "simply" by allowing yunohost to set your level at 3/4: https://yunohost.org/#/packaging_apps_levels_fr (I do not know where is the english version)

**Comment by bourreP** [comment]
Hi, I close this issue. If you need some help, you can response to this one or open another.
