### ISSUE TITLE
Upgrade error: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#71]
Nice, to learn we may be able to make partial backup soon! It don't seems easy to remove individually tagged images from the registry. (To allow rapid rollback, we have git commit hash tag on each CI execution of the deploying branches, this duration was for a 70Go registry storage, which backup then is archived in two long steps).

So my last upgrade failed and I don't really understand why in the logs, here the part I think contains the relevant data.

[logs](https://paste.yunohost.org/keluwiqomi.log)

note: I was migrating from a 11.11.1 gitlab version.

I can't resist to the temptation to add the timestamps of the lines which were time consuming in the process as the fact it was 5hours long was something noticeable  ^^.

Feel free to close this issue if you think it's not the relevant place to ask for help on this case.

**Comment by kay0u** [comment]
With this PR: https://github.com/YunoHost-Apps/gitlab_ynh/pull/73 you should be able to select what you want backup.
You can disable registry backup with something like that:

```
sudo yunohost app setting gitlab backup_registry -v 0
``` 

And launch the upgrade (to this PR, or wait this PR get merged to master)

For your issue, I don't understand well, can I get a complete log please? The upgrade should upgrade first to 11.11.5 and then to 12.x.x

**Comment by Christophe31** [comment]
That mean that If the issue happen again it will clear my registry?
It may even be a good news ^^ as it does not collect my images and it infinitely grow.

[full log quickly anonimised so I'm christophe31 on domain mydomain ^^](https://sebsauvage.net/paste/?c1056b58a80f55ff#5Xe/66nxQMG0hqlcrL4eLdSiunbdPijy2NV+0Y33NAc=)

Thanx for your time & support.

**Comment by kay0u** [comment]
You are not alone:
https://gitlab.com/gitlab-org/omnibus-gitlab/issues/4522#note_194481204
They're proposing a workaround but I don't understand it --' If it can help you...

**Comment by Christophe31** [comment]
hoo, I don't even remember why I have this in my persistent config file:
``` ruby
alertmanager['flags'] = {
    'cluster.advertise-address' => "127.0.0.1:9093",
    'web.listen-address' => "#{node['gitlab']['alertmanager']['listen_address']}",
    'storage.path' => "#{node['gitlab']['alertmanager']['home']}/data",
    'config.file' => "#{node['gitlab']['alertmanager']['home']}/alertmanager.yml"
}
```
I probably copied by mistake in my 13 lines files. I'm removing it.

**Comment by kay0u** [comment]
You're welcome!

I'll keep this issue open for now, waiting for your feedback.

**Comment by Christophe31** [comment]
I think I'll wait #73 to be in the next upgrade to try again.

**Comment by kay0u** [comment]
About the registry path, I found this command:

`gitlab-ctl registry-garbage-collect -m`

https://gitlab.com/gitlab-org/gitlab-ce/issues/25322

Could this solve your problem? (Use it only if you know what you are doing, and after reading the doc ;-))

**Comment by kay0u** [comment]
This could help too:
https://stackoverflow.com/questions/55361101/gitlab-container-registry-any-way-to-automate-deletion-of-old-containers

**Comment by Christophe31** [comment]
I already tryed ``gitlab-ctl registry-garbage-collect -m`` but it didn't worked as each of my container is tagged with it's own commit hash. (to ease quick rollback).

The stackoverflow solution seems to allow image deletion by commit hash with an other docker image but it don't look easy to clean all images except those older than a month or the last 3 of each branches. I readed gitlab added a tag deletion feature but it don't work when I use it in 11.11 even if I use my admin account. 12.0 allow to delete tagged images to developpers, and 12.2 allow to delete multiple in a single time.

**Comment by kay0u** [comment]
Ok.

In fact, after rethink of your problem and my solution implemented in #73, you will have the same problem again during this upgrade, because the backup script used during the upgrade is the script of the current version installed (so the backup present in the master branch for now), not the new one supposed to fix your issue.

After this upgrade, you won't have this problem again, as the backup used will have my fix.

**Comment by Christophe31** [comment]
Yes, that's why I'll wait for a weekend and upgrade a good time, once and for all ^^.

After this long, boring update, I'll update settings and clear old images ^^.
I thing I will be more light hearted the following updates ;-).

**Comment by kay0u** [comment]
It's merged

**Comment by Christophe31** [comment]
deployed with no issues, thx for all. Nice Profile pic <3.

**Comment by kay0u** [comment]
Hey,

Gitlab provide a new option in the gitlab.rb:

https://docs.gitlab.com/ee/raketasks/backup_restore.html#excluding-specific-directories-from-the-backup

https://github.com/YunoHost-Apps/gitlab_ynh/blob/12bc215c7689c7ccdb8af3b9d5a0cb6c1abcfb24/conf/gitlab.rb#L444

I could remove my work from #73, and let people use this line in the `/etc/gitlab/gitlab-persistent.rb` file. What do you think about that?

**Comment by Christophe31** [comment]
sound nice to me
