### ISSUE TITLE
Backup restoration as git can't update user folders

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/gitlab_ynh#74]
I didn't deployed last week but I had an issue in my registry since the backup recovery, the registry user was not the good one:

https://docs.gitlab.com/ee/raketasks/backup_restore.html#container-registry-push-failures-after-restoring-from-a-backup

**Comment by kay0u** [comment]
Hi,
Thank you for your report, this issue should be fixed by #75

**Comment by kay0u** [comment]
I tried to do that after a restore:

`sudo chown -R registry:registry /var/opt/gitlab/gitlab-rails/shared/registry/docker`

But I have the error: 
> chown: invalid user: ‘registry:registry’

Did you do something to "enable" the registry?

**Comment by Christophe31** [comment]
yes, a simple chown was my solution, I don't remember if I used the user id or the user name as I checked it in the passwd before.

**Comment by Christophe31** [comment]
here from my history: ``` chown registry -R /var/opt/gitlab/gitlab-rails/shared/registry/docker/registry/ ```

**Comment by kay0u** [comment]
Ok, maybe gitlab only creates the user `registry' if we use it...
