### ISSUE TITLE
Default Repo Storage to /home

### ISSUE THREAD

**Issue by scharc** [YunoHost-Apps/gitlab_ynh#79]
Maybe consider moving the default repo and file storage under /home/git*

**Comment by kay0u** [comment]
Hi,

Why do you want to move git project in this folder?

If you have particular need, you can use the file /etc/gitlab/gitlab-persistent.rb, I found this thread to move repo: https://stackoverflow.com/questions/19902417/change-the-data-directory-gitlab-to-store-repos-elsewhere, but in a simple use, I see no advantage in moving this folder
