### ISSUE TITLE
No 32?

### ISSUE THREAD

**Issue by pierrechtux** [YunoHost-Apps/gitlab_ynh#83]
"Not compatible with a 32-bit architecture."
=> what a pity.
I live in Gers (32), and my good old yunohost machine has a 32 bit architecture...

Should I move to Bask Country (not to mention Béarn), 64?

I guess I should look at the dependencies, check out which one doesn't run on 32 bit machines, hack its code until success.  Tomorrow.

**Comment by frju365** [comment]
In fact, Gitlab is not compatible with 32Bit Architecture (cf. README.md). BUT : Gitea, another nice git host interface, may work on 32-bits archiecture : https://github.com/YunoHost-Apps/gitea_ynh

**Comment by pierrechtux** [comment]
Thanks!
I had already found gitea, I'm installing it right now...
Done.

**Comment by kay0u** [comment]
You should consider moving to Bask Country indeed ;-)

More seriously, Gitlab needs a lot of RAM to work properly, and "Omnibus Gitlab" (bundle I use to install Gitlab for YunHost) is the easiest way to install Gitlab, doesn't provide a 32 bit version. A solution would be to install Gitlab from the source but it's much more complicated to set up, and I don't have that time.

Unfortunately, for the moment this is a limitation for YunoHost.
